ebean:
  migration:
    run: false
  ddl:
    generate: true
    run: false

datasource:
  default: mysql_production
  h2:
    username: root
    password: root
    url: jdbc:h2:mem:ingswproject
  mysql_localhost:
    username: guest
    password: guest
    url: jdbc:mysql://localhost:3306/ingswproject?sessionVariables=default_storage_engine=InnoDB
  mysql_production:
    username: c0ingsw
    password: H4wFjkT!
    url: jdbc:mysql://46.254.36.77:3306/c0ingsw?sessionVariables=default_storage_engine=InnoDB
  sqlite:
    username: root
    password: root
    url: jdbc:sqlite:ingswproject.db