ebean:
  migration:
    run: true
  ddl:
    generate: false
    run: false

datasource:
  default: mysql_localhost
  h2:
    username: root
    password: root
    url: jdbc:h2:mem:ingswproject
  mysql_localhost:
    username: guest
    password: guest
    url: jdbc:mysql://localhost:3306/ingswproject
  mysql_production:
    username: c0ingsw
    password: H4wFjkT!
    url: jdbc:mysql://v00xpk-idea.sphostserver.com:3306/c0ingsw
  sqlite:
    username: root
    password: root
    url: jdbc:sqlite:ingswproject.db