ebean:
  migration:
    run: true
  ddl:
    generate: true
    run: false

datasource:
  default: sqlite
  h2:
    username: root
    password: root
    url: jdbc:h2:mem:ingswproject
    driver: org.h2.Driver
  sqlite:
    username: root
    password: root
    url: jdbc:sqlite:ingswproject.db
    driver: org.sqlite.JDBC