ebean:
  migration:
    run: false
  ddl:
    generate: false
    run: false

datasource:
  default: h2
  h2:
    username: root
    password: root
    url: jdbc:h2:mem:ingswproject
    driver: org.h2.Driver