name: Build and Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+' # Match major version tags

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Build with Maven
        run: mvn clean package

      - name: Extract Maven project version
        run: echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
        id: maven_version

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ github.workspace }}/target/ingswproject*.jar
          artifactErrorsFailBuild: true
          allowUpdates: true
          makeLatest: true
          removeArtifacts: true
          tag: ${{ steps.maven_version.outputs.version }}
          name: ${{ steps.maven_version.outputs.version }}
          body: |
            ## [${{ steps.maven_version.outputs.version }}] - ${{ steps.date.outputs.date }}
            
            ---
            
            Automated release for version ${{ steps.maven_version.outputs.version }}.