name: Build and Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+' # Match major version tags

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Build with Maven
        run: mvn clean package

      - name: Verify version for release
        id: check_version
        run: |
          echo "##[set-output name=is_major;]false"
          if [[ "${GITHUB_REF_NAME}" =~ ^v([0-9]+)(\.0+)?$ ]]; then
            echo "##[set-output name=is_major;]true"
          fi

      - name: Create GitHub Release
        if: steps.check_version.outputs.is_major == 'true'
        uses: ncipollo/release-action@v1
        with:
          artifacts: target/ingswproject-${{ github.ref_name }}.jar
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: |
            ## [${{ github.ref_name }}] - ${{ steps.date.outputs.date }}
            
            ---
            
            Automated release for version ${{ github.ref_name }}.